### ISSUE TITLE
Tags included in the Boilerplate

### ISSUE THREAD

**Issue by khamer** [imarc/boilerplate-archived#10]
I'm stripping out things we don't use after a conversation with Marcel, Jeff, and Dave yesterday, so that the boilerplate won't bother to add styles for tags we never intend or plan to use. If we are going to use those tags on a specific site, we can add specific rules for those tags – we'd all rather be adding things than removing things from the boilerplate on new projects.

I've left support for `b` and `i`, as these are used by Redactor by default.

We should discuss `div.callout`, `div.highlight`, versus `<aside>`.

I've left `<section>` and `<article>` in as I think we should use those going forward, but we can talk about that too.

**Comment by mattsah** [comment]
Personally I feel aside and div should be given the possibility of having a callout or highlight class equally.  I don't consider aside a replacement or substitution for callouts or highlights.  Indeed, you might want to callout or highlight something that is not very related to the surrounding content.  The #1 example of an appropriate aside that I can think of is related links, which I don't think should be "called out" or highlighted at all.  If anything they should be toned down as to not be exaggerated compared to the primary content.

That being said, there are cases where an aside should be called out and/or highlighted, because it is an emphasized piece of related content.

My feeling has always been that asides should be played down, and can be safely ignored by a person focused on actual content which is the focus of that page, unless otherwise explicitly called out.

**Comment by khamer** [comment]
Looking at four of our most recent sites (AJH, iMarc, Wilson Elser, MSCPA Online):
- MSCPA and AJH have `div.callout` elements. AJH has also `div.callout_right`, `div.callout_left`, div.callout_full`.
- None have `div.highlight` elements, however iMarc has `section.highlight` elements.
- AJH has `div.aside` and `img.aside`, whereas iMarc has classless `aside` elements.

Looking at some older sites, it looks like we used to use `div.highlight` but don't seem to anymore.

**Comment by davetufts** [comment]
Matt said:

> I feel aside and div should be given the possibility of having a callout or highlight class equally.

I agree with that.

Handbook touches on this here - http://handbook.imarc.net/frontend#Content - though it should be updated once this is finalized.

I'm in favor of boilerplate offering defaults for more types of content than just the bare minimal. If people see how `<article>` or `<aside>` or `<p class="highlight">` or `<div class="callout">` are used in boilerplate they'll be more apt to use those as intended. If not, people will make up different ways to class a callout on each site.

I don't think `<article>` replaces `<div class="main">` so we might want to consider adding that as well.

**Comment by mattsah** [comment]
My understanding of article is that it should really only be used for article content.  I use it for summary article information in conjunction with the summary tag (or in my case a div with a class of summary) with no details and an anchor link of more.

Dave said:

> I'm in favor of boilerplate offering defaults for more types of content than just the bare minimal.

I remember a _long_ time ago when I first started on what became the fledgling ideas for inKLing that you commented on how much you really liked the empty selectors with comments around them.  Still visible in inKLing today:  https://github.com/dotink/inKLing/blob/master/inkling.css#L71

I would suggest developing a _large_ list of these which will take up negligible space once minimized and really having people review them and their semantic value after some good discussion on how we feel about them.

A few more notes:

The relationship as provided in the standard for what should/shouldn't be an aside is not very detailed.  I recently used it on HCRI buildout for what amounts to a "sidebar", under the impression that the side bar did contain related information for the main content, i.e. the main section was on research, and the aside contained latest publications with regards to research.  This seems an appropriate usage in my opinion, but I welcome feedback.

I _hate_ `.main` as a class.  When we're talking about columns I generally try to avoid classing them as much as possible an using more natural selectors, but this falls short in a lot of cases.  I would really like to find something capable of actually getting rid of `.torso` and replacing `.torso` and `.main` with something re-usable that identifies the significance of these elements as the major focus of a set of elements on the same level.  I kinda like '.principal' as it can be used as a noun and an adjective.

``` html
<header>
    ...
</header>
<div class="principal group">
    <h1>Research</h1>
    <nav>
        <ul class="secondary">
            <li>Secondary Nav Item #1</li>
            <li>...</li>
        </ul>
    </nav>
    <section class="principal">
        <h2>
            Working with the premier semantic research teams to bring
            you the best HTML possible
        </h2>
        <p>
            ...
        </p>
    </section>
    <div class="supplemental">
        <section>
            <h3>Latest Publications</h3>
            <article>
                <h4>Title of the publication</h4>
                <summary>
                    A useful summary of the article...
                </summary>
                <a class="more" href="#">Read the Full Article</a>
            </article>
        </section>
        <section>
            <h3>Partners</h3>
            <ul>
                <li><a href="#">W3C</a></li>
                <li>...</li>
            </ul>
        </section>
    </div>
</div>
<footer>
    ...
</footer>
```

**Comment by mattsah** [comment]
One more thing, I read an article the other day on Firefox OS stuff and they were showing some HTML.  It might be a good idea to see what they're using for some of their interfaces for apps.  They had a `suggested` class for example on the "OK" buttons in a pair of "Cancel" and "OK", I thought that was dead on.

**Comment by BillBushee** [comment]
Definition and usage of the article tag:

The <article> tag specifies independent, self-contained content.

An article should make sense on its own and it should be possible to distribute it independently from the rest of the site.

Potential sources for the <article> element:

```
Forum post
Blog post
News story
Comment
```

See http://www.w3schools.com/tags/tag_article.asp

**Comment by mattsah** [comment]
@BillBushee 

I think the "self-contained content" bit and the general feel of the other stuff is what's pulled from the standard there.  The w3c has it stated pretty clearly as, "The article element represents a section of content that forms an independent part of a document or site; for example, a magazine or newspaper article, or a blog entry."

I'm not sure w3schools (which has [other issues](http://w3fools.com/)) is right to say that a comment is an article, even by their own slight modification of the definition.  In what respect is a comment self-contained?  It is 100% tied to the article.

The question I have semantically is whether or not an article could for example cover a company bio, or some general piece of text which is not an "article" per se in the news sense.  Article in the "thing" sense could cover just about anything.... article of clothing, etc.

**Comment by khamer** [comment]
Just more data re: what's in Handbook VS in practice:
- Wilson Elser, MSCPA, and AJH use `div.section`, although iMarc does not.
- None use a `messaging` class.
-  AJH only uses `div.main` in SiteManager. Wilson Elser and MSCPA use `div.main` in blocks and in SiteManager. iMarc also uses `div.main`, and also has a `section.main` on the [hospital landing page](http://imarc.net/hospital), but that page is a mess – it might be worth looking at that page to figure out what problems we were overcoming.

**Comment by rmohns** [comment]
A comment on `.callout` and `.highlight` versus `<aside>`:

Matt wrote: _“…asides should be played down, and can be safely ignored by a person focused on actual content…”_

This, exactly. It's distressingly common for both content asides and supplemental links to be given more visual emphasis than the main article, for example, [AJH's sidebar links are twice the size of principal content](http://www.ajh.org/services_and_departments/6-maternity_care_amp_birth_center/view_department). (That said, most of iMarc's work in the few years has avoided this.)

So, I would encourage us to make a distinction between these kinds of content:
- **asides** are parenthetical content: if the reader view/reads this, that's nice, but it's not top priority
- **callouts** are content we _want_ to get extra attention, even at the expense of principal content
- **additional reading or next step content** to be consumed or acted upon after the principal content (traditionally this is sidebar content, but it is _not_ a peer of principal content)

Providing appropriate classes can help both Creative and UX to create appropriate styling for supplementary content without having to read the entire content of a page to determine what, exactly, it is.

**Comment by khamer** [comment]
Closing this issue - we resolved this in our last discussion.
