### ISSUE TITLE
Margin consistency

### ISSUE THREAD

**Issue by davetufts** [imarc/boilerplate-archived#11]
Do we want to be more consistent with margins? Some styles have margin top & bottom, others just margin bottom. I thought that we generally used just margin-bottom.

@marcelmoreau - thoughts?

In the current boilerplate:
- headings (h1-6): margin bottom (1.5em)
- p: margin top & bottom (1.5em each)
- blockquote, pre: margin top & bottom (2em each)
- lists: margin top & bottom (1em each)
- div messaging (errors, success): margin top & bottom (1em each) 

p tags inside messaging blocks have no margins:

``` html
<div class="info">
<p>We couldn't complete your request...</p>
<p>Go to the homepage and do something</p>
</div>
```

**Comment by khamer** [comment]
I'm not picky, I'd leave this up to @marcelmoreau and creative. Here's some data:

`<p>`
- imarc.net 0 top, 2em bottom
- AJH 0 top, 1.75em bottom
- Wilson Elser 0 top 1.4em bottom
- Rapid 7 0 top 1.5em bottom

`<h1>` through `<h6>`
- imarc.net 0 top .5em bottom
- AJH 0 top .3em bottom on some, 0 top 15px bottom on others (~.5em)
- Wilson Elser 0 top .5em top on `h1`, 0 top .2em bottom on the rest
- Rapid 7 0 top .5em bottom

`<blockquote>`
- imarc.net falls through to 1em top, 1em bottom.
- AJH falls through to 1em top, 1em bottom.
- Wilson Elser 1.5em top 1.5em bottom, although there's also a 15px bottom padding (~1.2em)
- Rapid 7 blockquote is reset to 0 margins/padding and not ever set

`<ol>` and `<ul>`
- imarc.net 0 top 2em bottom
- AJH 0 top 2em bottom
- Wilson Elser 0 top 1.4em bottom
- Rapid 7 reset to 0 padding 0 margin and not ever set

`<div class="error">` and other messaging
- imarc.net margin is 20px top 30px bottom (1.25em top 1.875em bottom), padding is 16px top 16px bottom (1em top 1em bottom)
- AJH margin is 1em top 1.5em bottom, padding is 15px top 10px bottom (~.9em top ~.6em bottom)
- Wilson Elser is 20px top 30px bottom (~1.4em top ~2.1em bottom), padding is 16px top 16px bottom (~1.14em top ~1.14em bottom)
- Rapid 7 doesn't seem to have these styles.

**Comment by khamer** [comment]
So, I suppose the most common/average would be

`<p>` 0 top 1.5em bottom
`<h1>` 0 top .5em bottom
`<blockquote>` 1em top 1em bottom (which is consistent with the default top margin if it wasn't reset)
`<ul>` 0 top 2em bottom
`<div class="error">` 1em top 1em bottom and 1em top padding and 1em bottom padding.

I'm happy to change these to anything we feel like.

**Comment by marcelmoreau** [comment]
I made these margins more consistent.
