### ISSUE TITLE
Switch markup placement of aside.primary and div.main

### ISSUE THREAD

**Issue by davetufts** [imarc/boilerplate-archived#13]
Semantically should div.main appear before aside.primary in the markup?

And if there were a left and right column, I'd think that div.main would still appear first in the markup.

**Comment by mattsah** [comment]
@davetufts 

Yeah, other than secondary navigation.  That seems to be the only exception in my mind, but I wouldn't class that into an aside generally.

**Comment by mattsah** [comment]
I should note that this becomes somewhat difficult to do in some situations

**Comment by khamer** [comment]
I don't have a preference. My only thought is that if this is for screen readers etc., going from primary navigation to content to secondary navigation might be more jarring than going from primary navigation to secondary navigation to content. If I was "tabbing through" fields, I'd expect nav => nav => content.

**Comment by khamer** [comment]
Let's see if we can't get some thoughts from @marcelmoreau or @spcbeck.

**Comment by jeffturcotte** [comment]
I'm not too concerned with this either, role="main" makes the main content area easily accessible. 

I'm no screen reader expert, but I swear that modern ones can recognize <nav> (or role="navigation") and jump. If we can confirm that is the case, than I say put .main first.

**Comment by marcelmoreau** [comment]
I think the [source order should match the visual](http://www.456bereastreet.com/archive/201103/source_order_and_display_order_should_match/). There was buzz for a while that placing the content earlier in the source could improve SEO, I do not think that's been proven.

So if secondary nav lives in a left column, it comes before .main. 

We should also followup with screen readers and how they use roles –  we also do not have a skip navigation link in our boilerplate which is a Section 508 guidelines.
