### ISSUE TITLE
Standards vs. Good Practice

### ISSUE THREAD

**Issue by mattsah** [imarc/boilerplate-archived#15]
This came up in chat the other day, and I wanted to bring up here as an issue for discussion and possible action.

IMO the use of `<meta charset="UTF-8" />` is a hack that we should avoid.  Although this is now in the HTML5 spec, it was brought into HTML5 based on the fact that browsers didn't bother to properly parse the meta tags within the first 512 bytes of HTML which are used to determine document characteristics.

The traditional way to set the character type was as part of the `content-type` which would normally be a `meta` tag with an `http-equiv` attribute:

``` html
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
```

Assuming HTML is being served to a user, the content-type header should contain the equivalent of the string in the content attribute above, in which case, the shortened meta tag we are using is redundant.  In the case of HTML which is loaded directly in a browser from a file, the browser is left to determine the content mime type in a document which does not provide the full meta tag as above.

In 99.9999% of cases this tag only needs to be written once, and realistically is not written by our developers at all, but is instead included in default templates.  I see no actual value of using the shortened tag which promotes the use of an isolated attribute born out of hacky browsers instead of the more complete http-equiv type which is content-type complete in the event the file accessed over HTTP.

I do, however, feel that there is much value in ascertaining and supporting best practices.  There are lots of things which are _possible_ to do in HTML5, as there are in any language, but we define and follow best practices to ensure the most robust, explanatory, and flexible methods are chosen and promoted for us, but also for the larger developer community -- if this is not the case, then I propose we remove the self-closing `/` at the end :trollface:, cause that's 100% valid too, and obviously at that point we're just trying to save characters.

**Comment by jeffturcotte** [comment]
Can you supply an example document where a particular browser does not render the page correctly without the full/traditional mime-type meta tag? (either over HTTP or by loading a file)

**Comment by davetufts** [comment]
Good points Matt, but there are so many other things that are more important. Handbook says "HTML pages should begin with by setting utf-8 in the content-type meta tag." Either the long form or short form accomplish that. Boilerplate and the example on Handbook use the short form.

**Comment by mattsah** [comment]
@jeffturcotte, Nope, to my knowledge all browsers (at least the ones we care about) "parse" the first 512 bytes and look for something like a meta tag with the string `charset="utf-8"` (and other permuations of it).  Paul Irish mentioned this in a talk on HTML5 boilerplate, although I don't remember the details, I'm pretty sure you could do something like `<meta who cares what thisdsfoihr2 w8eyf8nf923ht98tr information-0ischarset=utf-8youknow>` and it would **work**.  If not that exactly, then certainly something not far off.

This, of course, would not validate, but the principle in which it was pulled into the spec was not based on whether it was valid, as clearly the charset attribute for it was not prior to.

@davetufts, there are always things more important in one fashion or another, but I think it's an issue we can address.  I would be in favor of defining it more strictly in handbook if one is contingent on the other.

Perhaps I'm overlooking something, but I actually can't find in handbook, for example, where it says we should use self closing tags on elements which do not have a closing tag.  Or that we should use closing tags at all.  Maybe I'm completely off base, was an actual decision made that whatever is valid is OK to use?  I don't recall this always being the case -- perhaps it was defacto the case simply because we used XHTML and that enforced such rules, and by switching to HTML5 we are throwing those good practices out?

**Comment by khamer** [comment]
I agree with Dave – there are more important things to worry about. We are staying consistent with bigger, more popular boilerplates like h5bp and Twitter Bootstrap. There's no rule that forces the use of the long or short form, so feel free to use either, but we might as well leave the short form in Boilerplate.

**Comment by jeffturcotte** [comment]
I want to state for the record that @mattsah is correct: the long form is the "right" way and the HTML5 standard got it wrong. Still, as long as boilerplate uses the HTML5 doctype, we will use its bastardized charset meta tag.
