### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by jeffturcotte** [imarc/boilerplate-archived#20]
Should this project be branded at all? 

Obviously, we want it branded for our own use, but as an open project, wouldn't we want to default to be generic? Currently anybody using the project out of the box would be repurposing our palette for their own use. Just a discussion topic, no action necessary yet.

**Comment by davetufts** [comment]
I don't think it needs to be branded. Generic but polished would be ideal.

That's said, I'm not opposed to pulling in iMarc colors if we think a blue or pink would work well.

**Comment by marcelmoreau** [comment]
Don't think it needs our branding. It should utilize the most common elements iMarc uses in new projects. I am thinking background-color and image on the body is common. We are more or less doing a good job at this.

**Comment by khamer** [comment]
I'm not sure what the action item is here – is it already too branded? Do we need to remove  similarities? If not, we should close this out, as everyone seems to be on the same page.

**Comment by davetufts** [comment]
No specific action item now. Closing.

**Comment by jeffturcotte** [comment]
To close this out I would just say that, I took the iMarc brand colors into consideration when polishing. Going forward this will not necessarily be the case.
