### ISSUE TITLE
Inconsistent sections

### ISSUE THREAD

**Issue by davetufts** [imarc/boilerplate-archived#23]
We have three main sections: header.primary, .torso, footer.primary

```
header.primary,
.torso,
footer.primary {
    position: relative;
    margin: 0 0 2.5em;
}
```

We also have .mold to act as a container.

```
.mold {
    margin: 0 auto;
    max-width: 1024px;
    padding: 0 16px;
    position: relative;
}
```

For torso to be contained we do:
    < div class="torso mold" >

But we can't do < header class="primary mold" > or < footer class="primary mold" > because of specificity issues.

Should .mold's margin be !important ?

**Comment by jeffturcotte** [comment]
```
.mold {
    margin: inherit auto;
    etc.
}
```

**Comment by khamer** [comment]
We also need to change `margin: 0 0 Xem;` into `margin-bottom: Xem;` (and equivalent) all over the place too unless the zeroes are really necessary. (I think this is what Jeff meant, but he typed only half.)

**Comment by davetufts** [comment]
We updated the margins to be more specific, renamed mold to container, and all is well.
