### ISSUE TITLE
Structure still up to date?

### ISSUE THREAD

**Issue by davetufts** [imarc/boilerplate-archived#27]
http://imarc.github.io/boilerplate/structure

Is this page still accurate? (Structure, linked from the README)

**Comment by jeffturcotte** [comment]
No. But it's not too far off. @khamer don't you have a bookmarklet to generate this structure wireframe? if so, we should put it in this repo (first by moving the root path to /src to make room)

**Comment by khamer** [comment]
The structure page itself a lot nicer than what the bookmarklet does, I could probably improve the bookmarklet but I'm more inclined to just maintain and update the structure page, as we'll have more control over the result.

**Comment by jeffturcotte** [comment]
Hmm, this could become a real chore to maintain by hand. I don't know if we get enough value back. That said, the base structure doesn't change very often.

**Comment by davetufts** [comment]
Agreed - I don't think the work in maintaining it outweighs the high probability that it will still end up inaccurate vs just viewing the source of the demo page. My vote is to remove it.

**Comment by marcelmoreau** [comment]
I will remove this as I am about to push a bunch of stuff

**Comment by khamer** [comment]
We removed this information and all of the old, out of date references (which had pictures) from Handbook. I don't think that this information is useless, especially for new employees (which are the primary consumers of Handbook.)

I'm not even convinced this page is out of date enough to be problematic - it doesn't need to be the exact DOM that's part of the HTML for Boilerplate, just enough of the structure to provide a visual explanation of the structure we're using.

It seems silly to remove a page that only takes 2-3 lines to update and whose content rarely changes.

**Comment by jeffturcotte** [comment]
The info isn't useless but IMO the structure page would need a lot more work for it to be a valuable and polished presentation of such info. The handbook images worked so well because they had the context of a real web page, but this feels like a very rough prototype.

Web Inspector / Firebug does the job ;p

**Comment by davetufts** [comment]
I'll close this, as my question was answered. I really don't care what we do as long as that page was thought about and addressed.
