### ISSUE TITLE
Add copyright, info

### ISSUE THREAD

**Issue by davetufts** [imarc/boilerplate-archived#29]
Should we add a copyright, version, license to stylesheet?

Twitter Bootstrap uses something like this:

/*!
- Bootstrap v3.0.0
  *
- Copyright 2013 Twitter, Inc
- Licensed under the Apache License v2.0
- http://www.apache.org/licenses/LICENSE-2.0
  *
- Designed and built with all the love in the world by @mdo and @fat.
  */

**Comment by khamer** [comment]
Yeah, we should do one of the Mozilla (BSD?) style ones that says "Use this as thou will but if you do don't call it 'iMarc'" or whatever license we're content with.

As for the (dangerous) topic of version numbers, I say we
- declare it 1.0.0,
- reserve the first digit for rewrites/redesigns,
- use the second number for changes that require markup changes, and
- use the third number for changes that don't require changes to the markup.

We can be flexible to what requires a markup change, but it'd be an easy way to keep track. Also, whenever we do change the the version number going forward we should update the README.md with a changelog.

**Comment by davetufts** [comment]
Version: Agreed on all bullets
Copyright: iMarc, http://www.imarc.net
License: Yes, BSD seems appropriate.

**Comment by jeffturcotte** [comment]
We should add the copyright info. We should also just use the Apache License 2.0. It's more explicit about trademarks.

The versioning system is ideal, but we should also be conscious about major/minor releases and be sure to tag them, with master being the 'dev/bugfix' branch. If we're doing a changelog, we should put it in a separate file. (Bootstrap uses CHANGELOG.md)

**Comment by khamer** [comment]
I've added a reference to the copyright. I've also tagged 1.0.0, and put 1.0.0 into the SCSS.

**Going forward**, when we make changes
- If its a bug fix, we can make it directly on **gh-pages** (the branch we've all been working on.) If we have made enough changes that we want to up the version number and track it, we should up the third digit (1.0.0 -> 1.0.1) and make a new tag.
- If its a new feature or enhancement that **doesn't require markup changes**, we should do it on **master** (a new branch we will use for development.) To preview/test changes on **master**, you will have to download an view the changes locally. When we're happy, we'll merge the changes from **master** to **gh-pages**, up the third digit (1.0.0 -> 1.0.1) and make a new tag.
- If we're making changes that **require markup changes**, we should do it on **master**. When we're happy, we'll merge the changes from **master** to **gh-pages** and up the second digit (1.0.x -> 1.1.0) and make a new tag.
- If we ever make a whole new boilerplate, we'll pick how we want to deal with it then (either use **master** or make a new branch just for it most likely.)

@spcbeck and @marcelmoreau, you're the only others who I think have contributed to Handbook directly, so I wanted to make sure you saw this too. You can bug me if you're not sure what's up or want help pushing/switching to **master** from **gh-pages**.
