### ISSUE TITLE
LESS or SASS?

### ISSUE THREAD

**Issue by jeffturcotte** [imarc/boilerplate-archived#3]
http://lesscss.org/
http://sass-lang.com/

This could be a good project to try one or the other out. If we don't like it, we compile it at the end and leave it at that.

I'm currently leaning towards LESS for the only reason that it can be compiled client-side in JS. _Not that we would ever put it into production like that_, but it drops the technical barrier for testing it out (and UX/Creative contributing) to zero.

As for server side, Assetic supports both: https://github.com/kriswallsmith/assetic

**Comment by khamer** [comment]
This came up in UXJam, and Sean expressed a dislike for LESS and that he liked SASS (I assume with compasss) more. I'm all for investigating these things, but I think that sounds like a better project to choose to try out on one client site first and then go from there. Maybe on RSA even, which is likely to need a lot of CSS to support older browsers, and might give us a chance to really see how they'd work out.

for now, it'd be nice to get a boilerplate finished that matches what we currently do.

**Comment by mattsah** [comment]
I'm in favor of whichever one supports nested rulesets (probably both).  But particularly one if it supports a preceding qualifier, e.g.:

``` sass
.nav {
      /* rules */

      > ul {
           /*rules*/
      }
}
```

**Comment by khamer** [comment]
I'm going to close this, as I think this is best as part of a separate project.
