### ISSUE TITLE
Pick Icons

### ISSUE THREAD

**Issue by khamer** [imarc/boilerplate-archived#33]
After Issue #31, we talked some about the icons we have. Here's [a selection of 24 icons](http://jsfiddle.net/khamer/mNV8U/2/embedded/result/) from [FontAwesome](http://fortawesome.github.io/Font-Awesome/icons/).

I'm showing the icons at 12px and 14px, as small sizes is what brought up the issue the first time. **Please tell me what icons you would want to add or drop from what's available in FontAwesome.**

The FontAwesome font itself, as is, ranges from 37K (.eot) and 194K (.svg).

**I say** we just use the default FontAwesome font. We can come up with our own CSS for Boilerplate, so please ignore all the markup/CSS for FontAwesome.

Still, it'd be worth picking a small set of icons to 'showcase' on Boilerplate, use as defaults to be consistent, and so we can integrate them into things like Boilerplate messaging, etc.

If we're worried about the size of the FontAwesome font, then we can always make a stripped down version that only includes the subset of icons we like.

**Comment by khamer** [comment]
@marcelmoreau , @spcbeck , @davetufts, @jeffturcotte please weigh in when you get a chance. After this, I don't mind fixing Issue #31.

**Comment by davetufts** [comment]
I agree. Use those awesome font icons from FontAwesome.
