### ISSUE TITLE
Boilerplate 1.2 Tasks

### ISSUE THREAD

**Issue by khamer** [imarc/boilerplate-archived#37]
Just making a list of tasks to get done before merging 1.2 back:
- update FontAwesome files
- restructure sections to 1. webfonts 2. variables 3. mixins 4. base ...
- most likely remove query-label
- check whether the doubling of media queries is necessary anymore
- fontstack variables?
- update/verify gradient syntax

**Comment by marcelmoreau** [comment]
- ensure that fontawesome import syntax is also carried over
- remove grouping section. merge container into layout section and group into base
- can we use a simplified font-stack rather than using open sans, helvetica neue everywhere?

**Comment by khamer** [comment]
https://github.com/imarc/boilerplate/blob/1.2-proposed/css/styles.scss

I have addressed all the bullets above, and done testing with:
- Windows 8/Firefox 30
- Windows 8/Chrome 35
- Windows 8/IE 8 (via IETester)
- Windows 8/IE 9 (via IETester)
- Windows 8/IE 10 (via IETester)
- Windows 8/IE 11
- Linux/Chrome 35
- Linux/Chrome 36 (beta)
- Linux/Firefox 30
