### ISSUE TITLE
missing closing bracket

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-archived#38]
https://github.com/imarc/boilerplate/blob/gh-pages/js/bp.js#L6

no closing bracket here caused issues on WSI. Is this on purpose?

@jeffturcotte @khamer

**Comment by Tchanthaboune** [comment]
Looks fine to me

**Comment by albedoa** [comment]
Same.

**Comment by marcelmoreau** [comment]
Odd, as WSI's mobile nav would not work without this closing bracket.

**Comment by dtcollins** [comment]
@marcelmoreau you added the closing curly bracket and it was breaking the JS so I removed it. You must have been running into something else.

**Comment by marcelmoreau** [comment]
It looks like the takeaway here is: this script will cause complications if you are laying out your nav's list items with inline-block instead of block as was the case with WSI.
