### ISSUE TITLE
Change navigation to ULs and add support for .active

### ISSUE THREAD

**Issue by khamer** [imarc/boilerplate-archived#4]
After reviewing more markup per @mattsah 's comments, I'm going to revisit the markup here some. While `a` tags can be directly inside of `nav` elements and that's probably best for utility or 'in content' navigation, since the primary/secondary navigation is usually hierarchical it really still needs to be in lists. I'm opening the ticket so I don't forget.

**Comment by marcelmoreau** [comment]
How is utility nav "in-content"? I say these should be lists, too

**Comment by khamer** [comment]
Oh fine.
