### ISSUE TITLE
Tabs should have better mobile experience

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-archived#58]
On small screen, tabs could turn into accordions or have a general better experience

**Comment by mbfitz** [comment]
@marcelmoreau - Jeff and I refactored this plugin today on Diligent for the very same reason. We made it a little more flexible as far as markup goes, too. You can assign this to me and I can make the updates in a new PR on components. Thanks!

**Comment by mbfitz** [comment]
This has been done in PR 90 and we'll track any further updates there. 

https://github.com/imarc/boilerplate/pull/90
