### ISSUE TITLE
Messaging markup

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-archived#6]
I have always preferred using an outside div and a paragraph inside for messaging. It's often required to have two levels of tags to achieve site designs. RIght now, we only have a div and then text. The code below reflects what I'd like to see.

``` HTML
<div class="success">
    <p>
        <strong>Success</strong> – Message with a <a href="http://imarc.net">link</a>.
    </p>
</div>
```

**Comment by khamer** [comment]
http://www.wilsonelser.com/subscribe for example, has markup like

``` html
<div class="error">
    <p>The following problems were found:</p>
    <ul>
        <li>Name: Please enter a value</li>
        <li>Company: Please enter a value</li>
        <li>Email: Please enter a value</li>
        <li>Topic: Please enter a value</li>
    </ul>
</div>
```

I've tweaked the base markup to be an example of this, as well as tweaks the CSS to support this better.
