### ISSUE TITLE
stickyElement.js clean up

### ISSUE THREAD

**Issue by TommyChanthaboune** [imarc/boilerplate-archived#75]
- [ ] Include documentation in the component's HTML page as well

- [ ] Methods of FixedElement should use 'this' instead of 'that'

- [ ] Variables set to jQuery objects should be prefixed with `$`

- [ ] Clean up conditionals

**Comment by marcelmoreau** [comment]
should this be for the sticky element, not sticky header?

**Comment by TommyChanthaboune** [comment]
Yes you're right
