### ISSUE TITLE
Leftover styling and component placement

### ISSUE THREAD

**Issue by paulkelley** [imarc/boilerplate-archived#79]
There are styles for footer.primary here:
https://github.com/imarc/boilerplate/blob/gh-pages/css/styles.scss#L448

That are overwritten by the inclusion of the footer component here:
https://github.com/imarc/boilerplate/blob/gh-pages/css/styles.scss#L874

Is the earlier selection an accidental carry over? Should we be putting components as late in the sass file as we are? Seems to me you'd want to lead with base stuff so you can build on top of it.

(This is based on the assumption that the _components.scss file shouldn't be edited)

**Comment by paulkelley** [comment]
Same goes for the social styles, which are included in the component, but are also in styles.scss
https://github.com/imarc/boilerplate/blob/gh-pages/css/styles.scss#L466

How are we supposed to go about styling these things?

**Comment by marcelmoreau** [comment]
Paul thanks for commenting – this engagement is exactly what we're looking for. I went ahead and made a commit. Footer is no longer a dedicated component and it's baked in. Social icon styles are now tightened up. These styles appear outside the footer provided you want to use these within another element. Brought components higher in the SASS.
