### ISSUE TITLE
accordion should be structured differently

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-archived#81]
making a note of this here...

accordion should be structured differently to allow for more robust styling...see EduBoston landing page as an example.

**Comment by TommyChanthaboune** [comment]
@marcelmoreau Please elaborate on the issue.

**Comment by marcelmoreau** [comment]
instead of modifying classes on `.header` and `.content`, we should manipulate the parent `div`. This allows us to give the entire accordion row a class, which allows for more robust styling as seen in attachment
![screen shot 2017-02-16 at 10 09 55 am](https://cloud.githubusercontent.com/assets/2116946/23029463/a51c6fc8-f438-11e6-8bbb-eb7ae70c3472.png)
