### ISSUE TITLE
Register Boilerplate as an NPM package

### ISSUE THREAD

**Issue by TommyChanthaboune** [imarc/boilerplate-archived#96]
It would be great if I could 

`$ npm install imarc-boilerplate` 

or something

**Comment by khamer** [comment]
It's not that useful, but what you typed I setup a couple months ago - https://www.npmjs.com/package/imarc-boilerplate

**Comment by TommyChanthaboune** [comment]
Oh, I didn't know it was already registered. That's good to know.
